name: Add Custom Asset to Release

on:
  release:
    types: [published]

jobs:
  upload-addon-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version number from tag
        id: extract_version
        run: |
          VERSION=${{ github.ref_name }}
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Update version in files
        run: |
          # Replace version placeholders in TOC file
          sed -i "s/@VERSION@/${{ env.VERSION }}/g" AutoAdal/AutoAdal.toc
          # Replace version placeholder in Lua file
          sed -i "s/@VERSION@/${{ env.VERSION }}/g" AutoAdal/AutoAdal.lua

      - name: Copy README into AutoAdal
        run: cp README.md AutoAdal/

      - name: Zip AutoAdal folder with version tag in filename
        run: |
          zip -r AutoAdal-${{ github.ref_name }}.zip AutoAdal

      - name: Upload versioned zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: AutoAdal-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
